const { ethers } = require('ethers');
const wallet = new ethers.Wallet('86804e78cd7fe9706609d4a7e5ca0142996770239ff1b874c9dba2ff425b07df');
console.log('Address generated by config private key:', wallet.address);
